import Head from 'next/head'

const posts = [
  { title: 'React Training', excerpt: 'I am learning react from scratch' },
  { title: 'JavaScript Training', excerpt: 'I am an expert on JavaScript' },
]
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <h1 className='bg-pink-400 md:bg-purple-300 md:text-9xl'>Home Page</h1>
      </div>
    </div>
  )
}
